%STARTUP

%% add MATPOWER paths
addpath( ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/lib', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/lib/t', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/data', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/mips/lib', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/mips/lib/t', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/most/lib', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/most/lib/t', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/mptest/lib', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/mptest/lib/t', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/maxloadlim', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/maxloadlim/tests', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/maxloadlim/examples', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/misc', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/reduction', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/sdp_pf', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/se', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/smartmarket', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/state_estimator', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/syngrid/lib', ...
    '/home/monish/Projects/HELICS_Plus/matpower7.0/extras/syngrid/lib/t', ...
    '-end' );

%% add HELICS paths
addpath('/home/monish/Projects/Softwares/Helics_install/octave');